# Generated by Django 4.2.20 on 2025-04-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0006_csvimporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="query",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                verbose_name="search query for smart collection",
            ),
        ),
    ]
