# Generated by Django 4.2.11 on 2024-04-22 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_identity_indexable"),
        ("users", "0024_list"),
    ]

    operations = []
