# Generated by Django 4.2.20 on 2025-07-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_add_relay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="icon_uri",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="identity",
            name="image_uri",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
