# Generated by Django 5.2.16 on 2026-07-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_fanout_default_icon_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmessage",
            name="raw_document",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
