# Generated by Django 5.2.17 on 2026-08-09 08:08

import core.snowflake
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_inboxmessage_raw_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureAuthorization",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=core.snowflake.Snowflake.generate_identity,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collection_uri", models.CharField(max_length=2048)),
                (
                    "request_uri",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_authorizations",
                        to="users.identity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["identity", "collection_uri"],
                        name="users_featu_identit_4ed71d_idx",
                    )
                ],
            },
        ),
    ]
