# Generated by Django 5.2.17 on 2026-09-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_featureauthorization"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="canonical",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alias_identities",
                to="users.identity",
            ),
        ),
    ]
