# Generated by Django 5.2.5 on 2025-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial_0_11"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="mastodon_boost_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("journal.baseimporter", "base importer"),
                    ("journal.csvexporter", "csv exporter"),
                    ("journal.csvimporter", "csv importer"),
                    ("journal.doubanimporter", "douban importer"),
                    ("journal.doufenexporter", "doufen exporter"),
                    ("journal.goodreadsimporter", "goodreads importer"),
                    ("journal.letterboxdimporter", "letterboxd importer"),
                    ("journal.ndjsonexporter", "ndjson exporter"),
                    ("journal.ndjsonimporter", "ndjson importer"),
                    ("journal.opmlimporter", "opml importer"),
                    ("journal.steamimporter", "steam importer"),
                    ("journal.storygraphimporter", "story graph importer"),
                    ("journal.traktimporter", "trakt importer"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
