# Generated by Django 5.2.5 on 2025-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial_0_11"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="mastodon_boost_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
