coverage:
  status:
    project:
      default:
        informational: true
        branches:
          - "!main"
    patch:
      default:
        informational: true
        branches:
          - "!main"

flag_management:
  individual_flags:
    - name: neodb
      carryforward: true
    - name: takahe
      carryforward: true
