# Generated by Django 5.2.12 on 2026-03-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("takahe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="quote_url",
            field=models.CharField(
                blank=True, db_index=True, max_length=2048, null=True
            ),
        ),
    ]
