# Generated by Django 5.2.13 on 2026-04-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_webauthncredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="disabled_search_sources",
            field=models.JSONField(default=list),
        ),
    ]
