# Generated by Django 5.2.16 on 2026-07-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_apidentity_ix_apidentity_handle_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="bluesky_publish_records",
            field=models.BooleanField(default=False),
        ),
    ]
