# Generated by Django 5.2.17 on 2026-08-23 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_preference_bluesky_publish_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("journal.baseimporter", "base importer"),
                    ("journal.csvexporter", "csv exporter"),
                    ("journal.csvimporter", "csv importer"),
                    ("journal.doubanimporter", "douban importer"),
                    ("journal.doufenexporter", "doufen exporter"),
                    ("journal.goodreadsimporter", "goodreads importer"),
                    ("journal.letterboxdimporter", "letterboxd importer"),
                    ("journal.mastodonimporter", "mastodon importer"),
                    ("journal.ndjsonexporter", "ndjson exporter"),
                    ("journal.ndjsonimporter", "ndjson importer"),
                    ("journal.opmlimporter", "opml importer"),
                    ("journal.rymimporter", "rym importer"),
                    ("journal.steamimporter", "steam importer"),
                    ("journal.storygraphimporter", "story graph importer"),
                    ("journal.traktimporter", "trakt importer"),
                    ("journal.twitterimporter", "twitter importer"),
                    ("journal.wordpressexporter", "wordpress exporter"),
                    ("journal.wordpressimporter", "wordpress importer"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_id", models.IntegerField(db_index=True)),
                ("url", models.URLField(max_length=1000)),
                ("disabled", models.BooleanField(default=False)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("edited_time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "application_id"),
                        name="unique_user_app_webhook",
                    )
                ],
            },
        ),
    ]
