# Generated by Django 5.2.5 on 2025-09-08 22:13

from django.core.cache import cache
from django.db import migrations


def reset_trends(apps, schema_editor):
    """reset trends cache as the model class names changed"""
    cache.set("public_gallery", [], timeout=None)
    # DiscoverGenerator is rescheduled by Setup.run() after all migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_externalresource_catalog_extres_lookup_ids_gin"),
    ]

    operations = [
        migrations.RunPython(reset_trends),
    ]
