# Generated by Django 4.2.20 on 2025-04-24 03:46

from django.db import migrations

from catalog.common.migrations import enqueue_migration_job, reindex_20250424


def queue_reindex(apps, schema_editor):
    enqueue_migration_job(reindex_20250424)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_migrate_work"),
    ]

    operations = [
        migrations.RunPython(queue_reindex),
    ]
