# Generated by Django 4.2.20 on 2025-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_auto_reindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_protected",
            field=models.BooleanField(null=True),
        ),
    ]
