# Generated by Django 4.2.21 on 2025-05-24 17:00

from django.db import migrations

from catalog.common.migrations import (
    enqueue_migration_job,
    normalize_language_20250524,
)


def queue_job(apps, schema_editor):
    # skip key is "normalize_language" (renamed from "normalize_lang" when
    # migration enqueues were unified under enqueue_migration_job)
    enqueue_migration_job(normalize_language_20250524)


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0016_rename_item_primary_lookup_id_type_primary_lookup_id_value_catalog_ite_primary_0a089c_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(queue_job),
    ]
