# Generated by Django 4.2.21 on 2026-04-17

from django.db import migrations

from catalog.common.migrations import (
    enqueue_migration_job,
    normalize_genre_20260412,
    populate_credits_20260412,
)


def queue_job(apps, schema_editor):
    enqueue_migration_job(normalize_genre_20260412)
    enqueue_migration_job(populate_credits_20260412)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_people_alter_externalresource_id_type_and_more"),
    ]

    operations = [
        migrations.RunPython(queue_job),
    ]
