# Generated by Django 5.2.15 on 2026-06-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_itemsimilarity_userrecommendation"),
        ("users", "0012_task_rym_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("verified", "verified"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("matched", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_feed", "no feed url available for this item"),
                            ("fetch_failed", "unable to fetch or parse the feed"),
                            (
                                "no_match",
                                "no matching identity found in the feed description",
                            ),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("edited_time", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_creators",
                        to="catalog.item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_works",
                        to="users.apidentity",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "owner")},
            },
        ),
    ]
