# Enqueue an async backfill of ItemCredit from the deprecated
# ItemPeopleRelation table (see catalog.common.migrations).

from django.db import migrations, models

from catalog.common.migrations import (
    backfill_credits_from_relations_20260719,
    enqueue_migration_job,
)


def queue_job(apps, schema_editor):
    enqueue_migration_job(backfill_credits_from_relations_20260719)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0026_unify_metadata"),
    ]

    operations = [
        migrations.RunPython(queue_job, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="externalresource",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("wikidata", "WikiData"),
                    ("isbn10", "ISBN10"),
                    ("isbn", "ISBN"),
                    ("asin", "ASIN"),
                    ("issn", "ISSN"),
                    ("cubn", "CUBN"),
                    ("isrc", "ISRC"),
                    ("gtin", "GTIN UPC EAN"),
                    ("oclc", "OCLC Number"),
                    ("rss", "RSS Feed URL"),
                    ("imdb", "IMDb"),
                    ("tmdb_tv", "TMDB TV Series"),
                    ("tmdb_tvseason", "TMDB TV Season"),
                    ("tmdb_tvepisode", "TMDB TV Episode"),
                    ("tmdb_movie", "TMDB Movie"),
                    ("goodreads", "Goodreads"),
                    ("goodreads_work", "Goodreads Work"),
                    ("googlebooks", "Google Books"),
                    ("doubanbook", "Douban Book"),
                    ("doubanbook_work", "Douban Book Work"),
                    ("doubanmovie", "Douban Movie"),
                    ("doubanmusic", "Douban Music"),
                    ("doubangame", "Douban Game"),
                    ("doubandrama", "Douban Drama"),
                    ("doubandrama_version", "Douban Drama Version"),
                    ("bookstw", "BooksTW Book"),
                    ("readmoo", "Readmoo Book"),
                    ("bibliotekdk_edition", "Bibliotek.dk"),
                    ("bibliotekdk_ereolen", "eReolen.dk"),
                    ("bibliotekdk_work", "Bibliotek.dk"),
                    ("bandcamp", "Bandcamp"),
                    ("spotify_album", "Spotify Album"),
                    ("spotify_show", "Spotify Podcast"),
                    ("discogs_release", "Discogs Release"),
                    ("discogs_master", "Discogs Master"),
                    ("musicbrainz_releasegroup", "MusicBrainz Release Group"),
                    ("musicbrainz_release", "MusicBrainz Release"),
                    ("musicbrainz_artist", "MusicBrainz Artist"),
                    ("douban_personage", "Douban Personage"),
                    ("goodreads_author", "Goodreads Author"),
                    ("spotify_artist", "Spotify Artist"),
                    ("tmdb_person", "TMDB Person"),
                    ("openlibrary_author", "Open Library Author"),
                    ("igdb_company", "IGDB Company"),
                    ("igdb", "IGDB Game"),
                    ("bgg", "BGG Boardgame"),
                    ("steam", "Steam Game"),
                    ("itch", "itch.io"),
                    ("bangumi", "Bangumi"),
                    ("apple_podcast", "Apple Podcast"),
                    ("apple_music", "Apple Music"),
                    ("yt_music", "YouTube Music"),
                    ("fedi", "Fediverse"),
                    ("qidian", "Qidian"),
                    ("ypshuo", "Ypshuo"),
                    ("ao3", "Archive of Our Own"),
                    ("jjwxc", "JinJiang"),
                    ("openlibrary", "Open Library"),
                    ("openlibrary_work", "Open Library Work"),
                    ("mobygames", "MobyGames"),
                    ("storygraph", "StoryGraph"),
                    ("rateyourmusic_release", "RateYourMusic Release"),
                    ("anilist_anime", "AniList Anime"),
                    ("anilist_manga", "AniList Manga"),
                    ("mal_anime", "MyAnimeList Anime"),
                    ("mal_manga", "MyAnimeList Manga"),
                    ("mangaupdates", "MangaUpdates"),
                ],
                max_length=50,
                verbose_name="IdType of the source site",
            ),
        ),
        migrations.AlterField(
            model_name="itemlookupid",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wikidata", "WikiData"),
                    ("isbn10", "ISBN10"),
                    ("isbn", "ISBN"),
                    ("asin", "ASIN"),
                    ("issn", "ISSN"),
                    ("cubn", "CUBN"),
                    ("isrc", "ISRC"),
                    ("gtin", "GTIN UPC EAN"),
                    ("oclc", "OCLC Number"),
                    ("rss", "RSS Feed URL"),
                    ("imdb", "IMDb"),
                    ("tmdb_tv", "TMDB TV Series"),
                    ("tmdb_tvseason", "TMDB TV Season"),
                    ("tmdb_tvepisode", "TMDB TV Episode"),
                    ("tmdb_movie", "TMDB Movie"),
                    ("goodreads", "Goodreads"),
                    ("goodreads_work", "Goodreads Work"),
                    ("googlebooks", "Google Books"),
                    ("doubanbook", "Douban Book"),
                    ("doubanbook_work", "Douban Book Work"),
                    ("doubanmovie", "Douban Movie"),
                    ("doubanmusic", "Douban Music"),
                    ("doubangame", "Douban Game"),
                    ("doubandrama", "Douban Drama"),
                    ("doubandrama_version", "Douban Drama Version"),
                    ("bookstw", "BooksTW Book"),
                    ("readmoo", "Readmoo Book"),
                    ("bibliotekdk_edition", "Bibliotek.dk"),
                    ("bibliotekdk_ereolen", "eReolen.dk"),
                    ("bibliotekdk_work", "Bibliotek.dk"),
                    ("bandcamp", "Bandcamp"),
                    ("spotify_album", "Spotify Album"),
                    ("spotify_show", "Spotify Podcast"),
                    ("discogs_release", "Discogs Release"),
                    ("discogs_master", "Discogs Master"),
                    ("musicbrainz_releasegroup", "MusicBrainz Release Group"),
                    ("musicbrainz_release", "MusicBrainz Release"),
                    ("musicbrainz_artist", "MusicBrainz Artist"),
                    ("douban_personage", "Douban Personage"),
                    ("goodreads_author", "Goodreads Author"),
                    ("spotify_artist", "Spotify Artist"),
                    ("tmdb_person", "TMDB Person"),
                    ("openlibrary_author", "Open Library Author"),
                    ("igdb_company", "IGDB Company"),
                    ("igdb", "IGDB Game"),
                    ("bgg", "BGG Boardgame"),
                    ("steam", "Steam Game"),
                    ("itch", "itch.io"),
                    ("bangumi", "Bangumi"),
                    ("apple_podcast", "Apple Podcast"),
                    ("apple_music", "Apple Music"),
                    ("yt_music", "YouTube Music"),
                    ("fedi", "Fediverse"),
                    ("qidian", "Qidian"),
                    ("ypshuo", "Ypshuo"),
                    ("ao3", "Archive of Our Own"),
                    ("jjwxc", "JinJiang"),
                    ("openlibrary", "Open Library"),
                    ("openlibrary_work", "Open Library Work"),
                    ("mobygames", "MobyGames"),
                    ("storygraph", "StoryGraph"),
                    ("rateyourmusic_release", "RateYourMusic Release"),
                    ("anilist_anime", "AniList Anime"),
                    ("anilist_manga", "AniList Manga"),
                    ("mal_anime", "MyAnimeList Anime"),
                    ("mal_manga", "MyAnimeList Manga"),
                    ("mangaupdates", "MangaUpdates"),
                ],
                max_length=50,
                verbose_name="source site",
            ),
        ),
        migrations.AlterField(
            model_name="itempeoplerelation",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "Author"),
                    ("translator", "Translator"),
                    ("performer", "Performer"),
                    ("actor", "Actor"),
                    ("director", "Director"),
                    ("composer", "Composer"),
                    ("artist", "Artist"),
                    ("voice_actor", "Voice Actor"),
                    ("host", "Host"),
                    ("playwright", "Playwright"),
                    ("designer", "Designer"),
                    ("choreographer", "Choreographer"),
                    ("original_creator", "Original Creator"),
                    ("producer", "Producer"),
                    ("publisher", "Publisher"),
                    ("distributor", "Distributor"),
                    ("production_company", "Production Company"),
                    ("record_label", "Record Label"),
                    ("developer", "Developer"),
                    ("studio", "Studio"),
                    ("publishing_house", "Publishing House"),
                    ("troupe", "Troupe"),
                    ("crew", "Crew"),
                ],
                max_length=50,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="itemsimilarity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userrecommendation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="verifiedcreator",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_feed", "no feed url available for this item"),
                    ("fetch_failed", "unable to fetch or parse the feed"),
                    ("no_audio", "no audio episode found in the feed"),
                    (
                        "no_match",
                        "no matching identity found in the feed or its linked website",
                    ),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
