# Generated by Django 5.2.6 on 2025-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial_0_11"),
        ("users", "0002_preference_mastodon_boost_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelflogentry",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="StoryGraphImporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.task",),
        ),
        migrations.CreateModel(
            name="TraktImporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.task",),
        ),
    ]
