# Generated by Django 4.2.23 on 2025-07-19 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_smart_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamImporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.baseimporter",),
        ),
    ]
