# Generated by Django 5.2.14 on 2026-05-10 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0011_collection_catalog_item_nullable"),
        ("users", "0010_preference_disabled_search_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "piece_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="journal.piece",
                    ),
                ),
                (
                    "visibility",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Public"),
                            (1, "Followers Only"),
                            (2, "Mentioned Only"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("edited_time", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "remote_id",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("summary", models.TextField(blank=True, default="")),
                ("sensitive", models.BooleanField(default=False)),
                ("language", models.CharField(blank=True, default="", max_length=8)),
                ("attachments", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.apidentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "created_time"],
                        name="journal_art_owner_i_eca75a_idx",
                    ),
                    models.Index(fields=["remote_id"], name="article_remote_id_idx"),
                ],
            },
            bases=("journal.piece",),
        ),
    ]
