# Generated by Django 5.2.14 on 2026-05-10 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0012_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="edited_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
