# Generated by Django 5.2.16 on 2026-07-19 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0014_rymimporter_crosspostretry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelfMemberProgress",
            fields=[
                (
                    "shelf_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="current_progress",
                        serialize=False,
                        to="journal.shelfmember",
                    ),
                ),
                (
                    "progress_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "progress_value",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("edited_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
