# Generated by Django 5.2.17 on 2026-08-18 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0017_article_cover"),
        ("users", "0016_preference_bluesky_publish_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=500, null=True, upload_to="upload/"
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True, max_length=500, null=True, upload_to="upload/"
                    ),
                ),
                (
                    "remote_url",
                    models.CharField(blank=True, default="", max_length=2500),
                ),
                (
                    "remote_preview_url",
                    models.CharField(blank=True, default="", max_length=2500),
                ),
                ("mimetype", models.CharField(blank=True, default="", max_length=200)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=500
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="users.apidentity",
                    ),
                ),
                (
                    "pieces",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attachment_records",
                        to="journal.piece",
                    ),
                ),
            ],
            options={
                "ordering": ["created_time", "pk"],
                "indexes": [
                    models.Index(
                        fields=["owner", "created_time"],
                        name="journal_att_owner_i_9d2be5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("file", ""), _negated=True)
                        & models.Q(("file__isnull", False)),
                        fields=("file",),
                        name="attachment_file_unique_when_set",
                    )
                ],
            },
        ),
    ]
