# Generated by Django 5.2.17 on 2026-08-23 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0017_article_cover"),
        ("users", "0017_alter_task_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordpressExporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.task",),
        ),
        migrations.CreateModel(
            name="WordpressImporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.baseimporter",),
        ),
    ]
