# Generated by Django 5.2.17 on 2026-09-06 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0019_backfill_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitterImporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.baseimporter",),
        ),
    ]
