# Generated by Django 4.2.18 on 2025-06-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_pushnotification_icon"),
        ("activities", "0023_post_subject_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="api.application",
            ),
        ),
    ]
