# Generated by Django 5.2.12 on 2026-03-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0025_post_quote_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("boost", "Boost"),
                    ("mentioned", "Mentioned"),
                    ("liked", "Liked"),
                    ("followed", "Followed"),
                    ("follow_requested", "Follow Requested"),
                    ("boosted", "Boosted"),
                    ("quoted", "Quoted"),
                    ("announcement", "Announcement"),
                    ("identity_created", "Identity Created"),
                ],
                max_length=100,
            ),
        ),
    ]
