# Generated by Django 5.2.12 on 2026-03-30 22:13

import core.snowflake
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0026_alter_timelineevent_type"),
        ("users", "0031_inboxmessage_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=core.snowflake.Snowflake.generate_post,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_hash", models.CharField(max_length=64, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "last_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="activities.post",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="conversations", to="users.identity"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="activities.conversation",
            ),
        ),
        migrations.CreateModel(
            name="ConversationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unread", models.BooleanField(default=True)),
                ("dismissed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="activities.conversation",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_memberships",
                        to="users.identity",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["updated"], name="activities__updated_038a41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmembership",
            index=models.Index(
                fields=["identity", "dismissed"], name="activities__identit_f4a9fb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationmembership",
            unique_together={("identity", "conversation")},
        ),
    ]
