# Generated by Django 5.2.12 on 2026-03-29 07:19

import django.db.models.deletion
from django.db import migrations, models

import takahe.models


class Migration(migrations.Migration):
    dependencies = [
        ("takahe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="quote_url",
            field=models.CharField(
                blank=True, db_index=True, max_length=2048, null=True
            ),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=takahe.models.Snowflake.generate_post,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_hash", models.CharField(max_length=64, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "last_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="takahe.post",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conversations",
                        to="takahe.identity",
                    ),
                ),
            ],
            options={
                "db_table": "activities_conversation",
            },
        ),
        migrations.CreateModel(
            name="ConversationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unread", models.BooleanField(default=True)),
                ("dismissed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="takahe.conversation",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_memberships",
                        to="takahe.identity",
                    ),
                ),
            ],
            options={
                "db_table": "activities_conversationmembership",
                "unique_together": {("identity", "conversation")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="takahe.conversation",
            ),
        ),
    ]
