# Generated by Django 5.2.16 on 2026-07-19 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("takahe", "0002_post_quote_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(default="needs_fetch", max_length=100)),
                ("state_changed", models.DateTimeField(auto_now_add=True)),
                ("state_next_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "state_locked_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("url", models.CharField(db_index=True, max_length=2048, unique=True)),
                ("title", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("rich", "Rich"),
                        ],
                        default="link",
                        max_length=10,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "author_url",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "provider_name",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "provider_url",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("embed_html", models.TextField(blank=True, default="")),
                (
                    "image_url",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("blurhash", models.TextField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_referenced_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "activities_previewcard",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="preview_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="takahe.previewcard",
            ),
        ),
    ]
