# Generated by Django 4.2.11 on 2024-05-02 02:48

import api.models.push
from django.db import migrations, models
import django.db.models.deletion
import stator.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_token_push_subscription_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_changed", models.DateTimeField(auto_now_add=True)),
                ("state_next_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "state_locked_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("locale", models.CharField(default="en", max_length=2)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mention", "Mention"),
                            ("status", "Post"),
                            ("reblog", "Boost"),
                            ("follow", "Follow"),
                            ("follow_request", "Follow Request"),
                            ("favourite", "Favorite"),
                            ("poll", "Poll"),
                            ("update", "Update"),
                            ("admin.sign_up", "Account Signup"),
                            ("admin.report", "Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.CharField(max_length=500)),
                (
                    "state",
                    stator.models.StateField(
                        choices=[
                            ("sending", "sending"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                        ],
                        default="sending",
                        graph=api.models.push.PushNotificationStates,
                        max_length=100,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_notifications",
                        to="api.token",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
