# Generated by Django 5.2.12 on 2026-03-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_pushnotification_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("mention", "Mention"),
                    ("status", "Post"),
                    ("reblog", "Boost"),
                    ("follow", "Follow"),
                    ("follow_request", "Follow Request"),
                    ("favourite", "Favorite"),
                    ("poll", "Poll"),
                    ("update", "Update"),
                    ("quote", "Quote"),
                    ("admin.sign_up", "Account Signup"),
                    ("admin.report", "Report"),
                ],
                max_length=20,
            ),
        ),
    ]
