# Generated by Django 5.2.5 on 2025-08-20 00:34

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("catalog", "0001_initial_0_11"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="externalresource",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["other_lookup_ids"], name="catalog_extres_lookup_ids_gin"
            ),
        ),
    ]
