# Generated by Django 5.2.6 on 2025-09-07 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_externalresource_catalog_extres_lookup_ids_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.item",
                    ),
                ),
                (
                    "people_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                        ],
                        default="person",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("catalog.item",),
        ),
        migrations.CreateModel(
            name="ItemPeopleRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("translator", "Translator"),
                            ("performer", "Performer"),
                            ("actor", "Actor"),
                            ("director", "Director"),
                            ("composer", "Composer"),
                            ("artist", "Artist"),
                            ("voice_actor", "Voice Actor"),
                            ("host", "Host"),
                            ("publisher", "Publisher"),
                            ("distributor", "Distributor"),
                            ("production_company", "Production Company"),
                            ("record_label", "Record Label"),
                            ("developer", "Developer"),
                            ("studio", "Studio"),
                        ],
                        max_length=50,
                        verbose_name="role",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("edited_time", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_relations",
                        to="catalog.item",
                    ),
                ),
                (
                    "people",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_relations",
                        to="catalog.people",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["item", "role"], name="catalog_ite_item_id_df3230_idx"
                    )
                ],
                "unique_together": {("item", "people", "role")},
            },
        ),
    ]
