# Generated by Django 5.2.12 on 2026-04-12 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_people_itempeoplerelation"),
        ("catalog", "0003_reset_trends"),
    ]

    operations = []
