# Generated by Django 5.2.12 on 2026-04-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0005_alter_people_options_alter_externalresource_id_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcredit",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "author"),
                    ("translator", "translator"),
                    ("director", "director"),
                    ("playwright", "playwright"),
                    ("actor", "actor"),
                    ("artist", "artist"),
                    ("designer", "designer"),
                    ("composer", "composer"),
                    ("choreographer", "choreographer"),
                    ("performer", "performer"),
                    ("host", "host"),
                    ("orig_creator", "original creator"),
                    ("crew", "crew"),
                    ("publisher", "publisher"),
                    ("developer", "developer"),
                    ("production_company", "production company"),
                    ("record_label", "record label"),
                    ("distributor", "distributor"),
                    ("studio", "studio"),
                    ("troupe", "troupe"),
                ],
                max_length=100,
                verbose_name="role",
            ),
        ),
    ]
