# Generated by Django 5.2.12 on 2026-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_externalresource_id_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="itemcredit",
            index=models.Index(fields=["name"], name="catalog_ite_name_e5e0d7_idx"),
        ),
    ]
