# Generated by Django 4.2.18 on 2025-01-27 05:56

import django_rq
from django.conf import settings
from django.db import migrations

from catalog.common.migrations import merge_works_20250301


def merge_works(apps, schema_editor):
    skips = getattr(settings, "SKIP_MIGRATIONS", [])
    if "merge_works" in skips:
        print("(Skipped)", end="")
        return
    django_rq.get_queue("cron").enqueue(merge_works_20250301)
    print("(Queued)", end="")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_fix_soft_deleted_edition"),
    ]

    operations = [
        migrations.RunPython(merge_works),
    ]
