# Generated by Django 4.2.18 on 2025-01-27 05:56

from django.db import migrations

from catalog.common.migrations import (
    enqueue_migration_job,
    fix_bangumi_20250420,
    merge_works_20250301,
)


def merge_works(apps, schema_editor):
    enqueue_migration_job(merge_works_20250301)
    enqueue_migration_job(fix_bangumi_20250420)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_fix_soft_deleted_edition"),
    ]

    operations = [
        migrations.RunPython(merge_works),
    ]
