# Generated by Django 4.2.20 on 2025-04-24 03:46

import django_rq
from django.conf import settings
from django.db import migrations

from catalog.common.migrations import reindex_20250424


def queue_reindex(apps, schema_editor):
    skips = getattr(settings, "SKIP_MIGRATIONS", [])
    if "reindex" in skips:
        print("(Skipped)", end="")
    else:
        django_rq.get_queue("cron").enqueue(reindex_20250424)
        print("(Queued)", end="")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_migrate_work"),
    ]

    operations = [
        migrations.RunPython(queue_reindex),
    ]
