# Generated by Django 4.2.21 on 2025-05-24 17:00

from datetime import timedelta

import django_rq
from django.conf import settings
from django.db import migrations

from catalog.common.migrations import normalize_language_20250524


def queue_job(apps, schema_editor):
    skips = getattr(settings, "SKIP_MIGRATIONS", [])
    if "normalize_lang" in skips:
        print("(Skipped)", end="")
    else:
        django_rq.get_queue("cron").enqueue_in(
            timedelta(seconds=5), normalize_language_20250524
        )
        print("(Queued)", end="")


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0016_rename_item_primary_lookup_id_type_primary_lookup_id_value_catalog_ite_primary_0a089c_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(queue_job),
    ]
