# Generated by Django 4.2.21 on 2026-04-17

from django.db import migrations

from catalog.common.migrations import enqueue_migration_job, reindex_people_20260417


def queue_reindex(apps, schema_editor):
    enqueue_migration_job(reindex_people_20260417)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_normalize_genre_populate_credits"),
    ]

    operations = [
        migrations.RunPython(queue_reindex),
    ]
