# Generated by Django 5.2.5 on 2025-08-10 06:57

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration is a combination of all the migrations til 0.11.0
    """

    replaces = [
        ("mastodon", "0001_initial"),
        ("mastodon", "0002_add_api_domain_server_version"),
        ("mastodon", "0003_mastodonapplication_reachable"),
        ("mastodon", "0004_alter_mastodonapplication_api_domain_and_more"),
        ("mastodon", "0005_socialaccount"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MastodonApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="site domain name"
                    ),
                ),
                (
                    "app_id",
                    models.CharField(max_length=200, verbose_name="in-site app id"),
                ),
                (
                    "client_id",
                    models.CharField(max_length=200, verbose_name="client id"),
                ),
                (
                    "client_secret",
                    models.CharField(max_length=200, verbose_name="client secret"),
                ),
                (
                    "vapid_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="vapid key"
                    ),
                ),
                (
                    "star_mode",
                    models.PositiveIntegerField(
                        default=0, verbose_name="0: unicode moon; 1: custom emoji"
                    ),
                ),
                (
                    "max_status_len",
                    models.PositiveIntegerField(
                        default=500, verbose_name="max toot len"
                    ),
                ),
                ("is_proxy", models.BooleanField(blank=True, default=False)),
                ("proxy_to", models.CharField(blank=True, default="", max_length=100)),
                (
                    "api_domain",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="domain for api call"
                    ),
                ),
                (
                    "server_version",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="type and verion"
                    ),
                ),
                ("disabled", models.BooleanField(default=False)),
                ("last_reachable_date", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mastodon.blueskyaccount", "bluesky account"),
                            ("mastodon.emailaccount", "email account"),
                            ("mastodon.mastodonaccount", "mastodon account"),
                            ("mastodon.threadsaccount", "threads account"),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("uid", models.CharField(max_length=255)),
                ("handle", models.CharField(max_length=1000)),
                ("access_data", models.JSONField(default=dict)),
                ("account_data", models.JSONField(default=dict)),
                ("preference_data", models.JSONField(default=dict)),
                ("followers", models.JSONField(default=list)),
                ("following", models.JSONField(default=list)),
                ("mutes", models.JSONField(default=list)),
                ("blocks", models.JSONField(default=list)),
                ("domain_blocks", models.JSONField(default=list)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("last_refresh", models.DateTimeField(default=None, null=True)),
                ("last_reachable", models.DateTimeField(default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlueskyAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mastodon.socialaccount",),
        ),
        migrations.CreateModel(
            name="EmailAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mastodon.socialaccount",),
        ),
        migrations.CreateModel(
            name="MastodonAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mastodon.socialaccount",),
        ),
        migrations.CreateModel(
            name="ThreadsAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mastodon.socialaccount",),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["type", "handle"], name="index_social_type_handle"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["type", "domain", "uid"], name="index_social_type_domain_uid"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("domain"),
                django.db.models.functions.text.Lower("uid"),
                name="unique_social_domain_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                models.F("type"),
                django.db.models.functions.text.Lower("handle"),
                name="unique_social_type_handle",
            ),
        ),
    ]
