# Generated by Django 4.2.11 on 2024-04-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0021_merge_20240422_1905"),
        ("users", "0025_merge_0023_identity_indexable_0024_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="featured_tags_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="HashtagFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featurers",
                        to="activities.hashtag",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtag_features",
                        to="users.identity",
                    ),
                ),
            ],
            options={
                "unique_together": {("identity", "hashtag")},
            },
        ),
    ]
