# Generated by Django 4.2.13 on 2024-06-08 18:14
# DEPRECATED

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is a combination of all the migrations til 0.10.0
    """

    replaces = [
        ("social", "0001_initial"),
        ("social", "0002_initial"),
        ("social", "0003_alter_localactivity_template"),
        ("social", "0004_alter_localactivity_template"),
        ("social", "0005_alter_localactivity_template"),
        ("social", "0006_alter_localactivity_template"),
        ("social", "0007_alter_localactivity_owner"),
    ]

    initial = True

    dependencies = [
        ("users", "0001_initial_0_10"),
        ("journal", "0001_initial_0_10"),
    ]

    operations = []
