# Generated by Django 4.2.21 on 2025-05-21 18:49

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("social", "0001_initial_0_10"),
        ("social", "0002_delete_localactivity"),
    ]

    initial = True

    dependencies = []

    operations = []
