# Generated by Django 4.2.21 on 2025-05-21 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial_0_10"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocalActivity",
        ),
    ]
