# Generated by Django 4.2.11 on 2024-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0017_post_language"),
        ("activities", "0020_alter_postattachment_remote_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="language",
            field=models.CharField(blank=True, default=""),
        ),
    ]
