# Generated by Django 4.2.11 on 2024-04-29 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0021_merge_20240422_1905"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanout",
            name="subject_hashtag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fan_outs",
                to="activities.hashtag",
            ),
        ),
        migrations.AlterField(
            model_name="fanout",
            name="type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("post_edited", "Post Edited"),
                    ("post_deleted", "Post Deleted"),
                    ("interaction", "Interaction"),
                    ("undo_interaction", "Undo Interaction"),
                    ("identity_edited", "Identity Edited"),
                    ("identity_deleted", "Identity Deleted"),
                    ("identity_created", "Identity Created"),
                    ("identity_moved", "Identity Moved"),
                    ("tag_featured", "Tag Featured"),
                    ("tag_unfeatured", "Tag Unfeatured"),
                ],
                max_length=100,
            ),
        ),
    ]
