# Generated by Django 4.2.11 on 2024-05-02 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0022_fanout_subject_hashtag_alter_fanout_type"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE activities_timelineevent SET subject_identity_id = activities_post.author_id
            FROM activities_post
            WHERE activities_timelineevent.type = 'post'
            AND activities_timelineevent.subject_post_id = activities_post.id
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
