# Generated by Django 5.2.16 on 2026-07-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0031_quoteauthorization"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanout",
            name="subject_document",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fanout",
            name="type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("post_edited", "Post Edited"),
                    ("post_deleted", "Post Deleted"),
                    ("interaction", "Interaction"),
                    ("undo_interaction", "Undo Interaction"),
                    ("identity_edited", "Identity Edited"),
                    ("identity_deleted", "Identity Deleted"),
                    ("identity_created", "Identity Created"),
                    ("identity_moved", "Identity Moved"),
                    ("tag_featured", "Tag Featured"),
                    ("tag_unfeatured", "Tag Unfeatured"),
                    ("forward", "Forward"),
                ],
                max_length=100,
            ),
        ),
    ]
